---
title: "(De/En)coding Experiments"
---

## Objective

Find tools that can provide the following:

1. decode and encode different types of videos with different representations
2. time/#instructions/power consumption for decoding and encoding
3. video quality metrics for the encoded videos

For (1) there is FFMPEG. For (2) nothing. For (3) there are some tools but none is exatcly what is needed.

## Movie File
For the experiments I used initially [bigbuckbunny](www.bigbuckbunny.org) movie:  
[http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4]

## FFMPEG - decode and encode
See details for decoding and encoding video with [ffmpeg](./ffmpeg.html).

## Metrics tools

### Process Information

* [DTrace](http://en.wikipedia.org/wiki/DTrace)
* [top, vm_stat, iostat](http://macperformanceguide.com/Mac-Monitoring-command-line.html) , [spindump](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/spindump.8.html)

### Video Quality Measurement

* [Stack Overflow question about tools](http://superuser.com/questions/338725/compare-two-video-files-to-find-out-which-has-best-quality)
* [Russian Tool](http://compression.ru/video/quality_measure/video_measurement_tool_en.html) windows, free version have no batch or command line, many QoE metrics
* [yuvtoolkit](http://yuvtoolkit.com) yuv reader, PSNR, MSE, open-source, comparison visualization
* [video-tester](https://code.google.com/p/video-tester/) video tester on python, open-source, does too much, as such streamer server
* (http://www.imagemagick.org/Usage/compare/)


### Others
* https://support.xsplit.com/forum/viewtopic.php?f=3&t=13768
